web-ruby-rails6-1/system/src/config/routes.rb
Rails.application.routes.draw do
  resources :topics
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

web-ruby-rails6-1/system/src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web-ruby-rails6-1/system/src/app/models/topic.rb
class Topic < ApplicationRecord
end

web-ruby-rails6-1/system/src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web-ruby-rails6-1/system/src/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        #format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        #format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      
      db_param = {
        "id" => topic_params[:"id"], 
        "name" => topic_params[:"name-selected"], 
        "toc" => topic_params[:"toc-selected"], 
        "memo" => topic_params[:"memo-selected"], 
      }
      
      if @topic.update(db_param)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
      #  format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
      #  format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic      
      @topic = Topic.find(params[:id])
      Rails.logger.debug "@topic"
      Rails.logger.debug @topic.inspect

    end

    # Only allow a list of trusted parameters through.
    def topic_params
      Rails.logger.debug "params"
      Rails.logger.debug params
      #params.require(:topic).permit(:name, :toc, :memo)
      params.permit(:"id", :"name-selected", :"toc-selected", :"memo-selected")
    end
end

web-ruby-rails6-1/system/src/app/helpers/application_helper.rb
module ApplicationHelper
end

web-ruby-rails6-1/system/src/app/helpers/topics_helper.rb
module TopicsHelper
end

web-ruby-rails6-1/system/src/app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Html</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap -->
    <link href="/bootstrap-5.0.2-dist/css/bootstrap.css" rel="stylesheet">
    <script src="/bootstrap-5.0.2-dist/js/bootstrap.js"></script>
    
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <!-- jQuery --> 
    <script src="/jquery/jquery-3.6.3.js"></script>
    

  </head>

   <body class="container bg-light">
        
  <div class="contents my-5 d-flex flex-row">
      
      <div class="list-area col-8 m-4 p-4 d-flex flex-column shadow p-3 mb-5 bg-body rounded rounded-3 bg-light" style="height:70vh;">
          
          <div class="row mb-3">
              リスト
          </div>

          <div class="row mb-3" style="height:60vh;overflow-y:scroll;">
              <table class="table table-hover" >
                  <thead>
                      <tr>
                          <th scope="col">#</th>
                          <th scope="col">名称</th>
                          <th scope="col">作成日時</th>
                          <th scope="col">更新日時</th>
                          <th scope="col">操作</th>
                      </tr>
                  </thead>
                  <tbody>
                    <% @topics.each do |topic ,i| %>
                        <tr class="select-detail-tr" id="row-index-<%= i %>">
                            <td><%= topic.id %></td>
                            <td><%= topic.name %></td>
                            <td><%= topic.created_at %></td>
                            <td><%= topic.updated_at %></td>
                            <td class="px-0 mx-0">
                                <div class="d-flex">
                                    <div class="me-3">
                                        <span type="button" name="edit-icon" class="material-symbols-outlined">
                                            edit
                                        </span>
                                    </div>
                                    <div>
                                        <span type="button" name="delete-icon" class="material-symbols-outlined">
                                            delete
                                        </span>
                                    </div>
                                </div>
                            </td>
                            <input name="id" value="<%= topic.id %>" type="hidden">
                            <input name="name" value="<%= topic.name %>" type="hidden">
                            <input name="toc" value="<%= topic.toc %>" type="hidden">
                            <input name="memo" value="<%= topic.memo %>" type="hidden">
                        </tr>
                    <% end %>

                  </tbody>
              </table>
              <form name="list-form" action="/" method="post">
                  @method('delete')
                  @csrf
              </form>

          </div>

          <div class="row justify-content-end me-2">
              <!-- 
              <button type="button" class="btn btn-outline-dark" style="width:10%;">
              </button> -->
              <span type="button" class="new-button p-2 shadow material-symbols-outlined " 
                  style="width:5%;background-color:#EEEEEE;border-radius:50%;">
                  add
              </span>
          </div>
          
      </div>
      
      <div class="detail-area col-4 m-4 p-4 d-flex flex-column shadow p-3 mb-5 bg-body rounded rounded-3 bg-light">
          <form name="detail-form" action="/" method="post">
              @csrf

              <div class="row mb-3">
                  詳細
                  <input name="id-selected" value="" type="hidden">
              </div>
              
              <div class="row mb-4">

                  <div class="mb-3">
                      <label for="name-selected" class="form-label">名称</label>
                      <input name="name-selected" id="name-selected" value="" class="form-control" type="text">
                  </div>

                  <div class="mb-3">
                      <label for="toc-selected" class="form-label">内容</label>
                      <textarea name="toc-selected" id="toc-selected" class="form-control" rows="10"></textarea>
                  </div>

                  <div class="mb-3">
                      <label for="memo-selected" class="form-label">メモ</label>
                      <textarea name="memo-selected" id="memo-selected" class="form-control" ></textarea>
                  </div>

              </div>

              <div class="row justify-content-end me-2">
                  <button type="button" class="create-button btn btn-outline-primary" style="display:none;width:20%;">登録</button>
                  <button type="button" class="update-button btn btn-outline-primary" style="display:none;width:20%;">更新</button>
              </div>

          </form>
      </div>
  
  </div>

</body>

<script>
$(function() {

  console.log('loaded.');

  // 
  $('.new-button').on('click',function(e){

      $("input[name='name-selected']").val('');
      $("textarea[name='toc-selected']").val('');
      $("textarea[name='memo-selected']").val('');

      $('.update-button').hide();
      $('.create-button').show();

    });

    // 更新
    $('.update-button').on('click',function(e){

        const targetId = $("input[name='id-selected']").val();

        if(targetId){
            //alert("{{ url('/topics/') }}/" + targetId)
            const url = "/topics/" + targetId;
            $("form[name='detail-form']").attr('action',url);
            $("form[name='detail-form']").attr('method','post');
            $("form[name='detail-form']").submit();

        }

    });

    // 登録
    $('.create-button').on('click',function(e){
        
        const url = "/topics/";
        $("form[name='detail-form']").attr('action',url);
        $("form[name='detail-form']").attr('method','post');
        $("form[name='detail-form']").submit();

    });

    // テーブル行選択
    $('.select-detail-tr').on('click',function(e){
        
        console.log($(this))
        console.log($(e.target).attr('name'))

        $(this).find("input[name='id']").val()
        const targetId = $(this).find("input[name='id']").val();
        console.log(targetId)

        if( $(e.target).attr('name') === 'delete-icon') {

            
            
            if(targetId){


                const url = "/topics/" + targetId;
                $("form[name='list-form']").attr('action',url);
                $("form[name='list-form']").attr('method', 'post');
                $("form[name='list-form']").submit();

                alert('削除していいですか ' + url)

            
            }

        }

        if( $(e.target).attr('name') === 'edit-icon') {
            // alert('編集')
            //const id = $(this).find("input[name='id']").val();
            $("input[name='id-selected']").val(targetId);

            const name = $(this).find("input[name='name']").val();
            $("input[name='name-selected']").val(name);

            const toc = $(this).find("input[name='toc']").val();
            console.log(toc)
            $("textarea[name='toc-selected']").val(toc);

            const memo = $(this).find("input[name='memo']").val();
            $("textarea[name='memo-selected']").val(memo);

            $('.create-button').hide();
            $('.update-button').show();
        }
    
    });


});
</script>

</html>

web-ruby-rails6-1/system/src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Html</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

web-ruby-rails6-1/system/src/app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :toc %>
    <%= form.text_area :toc %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_field :memo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

web-ruby-rails6-1/system/src/app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>
<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

<form name="detail-form" action="/topics/3" method="post">

  <button type="submit" value="">登録</button>

  # <input type="hidden" name="_method" value="patch" autocomplete="off">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

</form>

web-ruby-rails6-1/system/src/app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Toc</th>
      <th>Memo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.toc %></td>
        <td><%= topic.memo %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

web-ruby-rails6-1/system/src/app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

web-ruby-rails6-1/system/src/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Toc:</strong>
  <%= @topic.toc %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @topic.memo %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>